port: 80
routes:
  - route: "/test1/{param_1}/{param_2}"
    method: "GET"
    backends:
    - host: "http://localhost:1337" 
      url: "/api/services"
      method: "GET"
    - host: "http://localhost:1337" 
      url: "/api/products"
      method: "GET"
  - route: "/test2"
    method: "GET"
    backends:
    - host: "http://localhost:1337" 
      url: "/api/products"
      method: "GET"
